//! Prefixes that can never legitimately be the source of a packet.
//!
//! Generated by `scripts/gen-bogons.sh` from the IANA special-purpose registries.
//! Do not edit by hand: `gen-bogons.sh --check` refuses a table that is not what the
//! registries say, and a hand edit here is a rule nobody can trace back to a source.
//!
//! The RFC 1918 ranges are deliberately absent. A host behind NAT receives them, and
//! dropping them by default is the false positive every bogon list has shipped at
//! least once. The reasoning for each omission is in the script.

use lorica_common::LpmKey;

pub const BOGONS: [LpmKey; 28] = [
    LpmKey::v4([0, 0, 0, 0], 8),          // This network, RFC 791
    LpmKey::v4([0, 0, 0, 0], 32),         // This host on this network, RFC 1122
    LpmKey::v4([127, 0, 0, 0], 8),        // Loopback, RFC 1122
    LpmKey::v4([169, 254, 0, 0], 16),     // Link Local, RFC 3927
    LpmKey::v4([192, 0, 0, 0], 24),       // IETF Protocol Assignments, RFC 6890
    LpmKey::v4([192, 0, 0, 0], 29),       // IPv4 Service Continuity Prefix, RFC 7335
    LpmKey::v4([192, 0, 0, 8], 32),       // IPv4 dummy address, RFC 7600
    LpmKey::v4([192, 0, 0, 170], 32),     // NAT64/DNS64 Discovery, RFC 8880
    LpmKey::v4([192, 0, 0, 171], 32),     // NAT64/DNS64 Discovery, RFC 8880
    LpmKey::v4([192, 0, 2, 0], 24),       // Documentation (TEST-NET-1), RFC 5737
    LpmKey::v4([192, 88, 99, 2], 32),     // 6a44-relay anycast address, RFC 6751
    LpmKey::v4([198, 18, 0, 0], 15),      // Benchmarking, RFC 2544
    LpmKey::v4([198, 51, 100, 0], 24),    // Documentation (TEST-NET-2), RFC 5737
    LpmKey::v4([203, 0, 113, 0], 24),     // Documentation (TEST-NET-3), RFC 5737
    LpmKey::v4([224, 0, 0, 0], 4),        // Multicast, RFC 5771
    LpmKey::v4([240, 0, 0, 0], 4),        // Reserved, RFC 1112
    LpmKey::v4([255, 255, 255, 255], 32), // Limited Broadcast, RFC 8190
    LpmKey::v6(
        0x00000000_00000000_00000000_00000000_u128.to_be_bytes(),
        128,
    ), // ::/128, Unspecified Address, RFC 4291
    LpmKey::v6(
        0x00000000_00000000_00000000_00000001_u128.to_be_bytes(),
        128,
    ), // ::1/128, Loopback Address, RFC 4291
    LpmKey::v6(0x01000000_00000000_00000000_00000000_u128.to_be_bytes(), 64), // 100::/64, Discard-Only Address Block, RFC 6666
    LpmKey::v6(0x01000000_00000001_00000000_00000000_u128.to_be_bytes(), 64), // 100:0:0:1::/64, Dummy IPv6 Prefix, RFC 9780
    LpmKey::v6(0x20010000_00000000_00000000_00000000_u128.to_be_bytes(), 23), // 2001::/23, IETF Protocol Assignments, RFC 2928
    LpmKey::v6(0x20010002_00000000_00000000_00000000_u128.to_be_bytes(), 48), // 2001:2::/48, Benchmarking, RFC 5180
    LpmKey::v6(0x20010db8_00000000_00000000_00000000_u128.to_be_bytes(), 32), // 2001:db8::/32, Documentation, RFC 3849
    LpmKey::v6(0x3fff0000_00000000_00000000_00000000_u128.to_be_bytes(), 20), // 3fff::/20, Documentation, RFC 9637
    LpmKey::v6(0x5f000000_00000000_00000000_00000000_u128.to_be_bytes(), 16), // 5f00::/16, Segment Routing (SRv6) SIDs, RFC 9602
    LpmKey::v6(0xfe800000_00000000_00000000_00000000_u128.to_be_bytes(), 10), // fe80::/10, Link-Local Unicast, RFC 4291
    LpmKey::v6(0xff000000_00000000_00000000_00000000_u128.to_be_bytes(), 8), // ff00::/8, Multicast, RFC 4291
];
