#!/usr/bin/env bash
# Regenerate the bogon table from the two IANA special-purpose registries.
#
#   gen-bogons.sh           rewrite the committed table
#   gen-bogons.sh --check   exit non-zero when the committed table differs
#
# The table is a const in the binary, so an update to the registries is a diff a
# reviewer reads and never a fetch on the boot path. This script is the only thing
# that touches the network, and it runs when a human asks it to.

set -euo pipefail

repo=$(cd "$(dirname "$0")/.." && pwd)
out=$repo/crates/carapace-policy/src/compile/bogon_table.rs

v4_url=https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry-1.csv
v6_url=https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry-1.csv

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

fetch() {
    if ! curl -fsS --max-time 30 -o "$2" "$1"; then
        printf 'gen-bogons: could not fetch %s\n' "$1" >&2
        printf 'gen-bogons: the registries are the source of the table and there is no cached\n' >&2
        printf '            copy, so this run says nothing about whether the committed table\n' >&2
        printf '            is current. It is not a pass.\n' >&2
        exit 2
    fi
}

fetch "$v4_url" "$tmp/v4.csv"
fetch "$v6_url" "$tmp/v6.csv"

python3 - "$tmp/v4.csv" "$tmp/v6.csv" >"$tmp/bogon_table.rs" <<'PY'
import csv
import ipaddress
import re
import sys

# A block the registry marks as not globally reachable can never be the source of a
# packet that crossed the internet. That column is the rule; everything below is the
# short list of places where obeying it blindly would filter traffic a leaf host
# legitimately receives, or would filter the whole internet.
EXCLUDED = {
    # RFC 1918. A host behind NAT receives these all day and dropping them by default
    # is the classic false positive of every bogon list ever shipped.
    "10.0.0.0/8": "RFC 1918, legitimate behind NAT",
    "172.16.0.0/12": "RFC 1918, legitimate behind NAT",
    "192.168.0.0/16": "RFC 1918, legitimate behind NAT",
    # Same argument one layer out: the operator may be inside the carrier NAT.
    "100.64.0.0/10": "shared address space, legitimate behind a carrier NAT",
    # Same argument in IPv6.
    "fc00::/7": "unique-local, the IPv6 RFC 1918",
    "64:ff9b:1::/48": "local-use translation, legitimate behind a local NAT64",
    # The mapped range is the key the unified list is built on: a /96 entry here
    # would be one prefix covering every IPv4 address in existence.
    "::ffff:0:0/96": "the v4-mapped range the unified key itself uses",
}

# Multicast is not in either special-purpose registry, it has its own. It is a
# destination and never a source, which is the whole question this table answers.
EXTRA = [
    ("224.0.0.0/4", "Multicast", "RFC 5771"),
    ("ff00::/8", "Multicast", "RFC 4291"),
]


def rows(path):
    with open(path, newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            if not row["Globally Reachable"].startswith("False"):
                continue
            name = row["Name"].strip('"')
            rfc = re.search(r"RFC\s*(\d+)", row["RFC"])
            rfc = f"RFC {rfc.group(1)}" if rfc else "no RFC"
            for spec in row["Address Block"].split(","):
                spec = re.sub(r"\s*\[\d+\]", "", spec).strip()
                if spec in EXCLUDED:
                    continue
                yield spec, name, rfc


def entries(path):
    out = []
    for spec, name, rfc in rows(path):
        out.append((ipaddress.ip_network(spec), name, rfc))
    for spec, name, rfc in EXTRA:
        out.append((ipaddress.ip_network(spec), name, rfc))
    out.sort(key=lambda item: (int(item[0].network_address), item[0].prefixlen))
    return out


v4 = [e for e in entries(sys.argv[1]) if e[0].version == 4]
v6 = [e for e in entries(sys.argv[2]) if e[0].version == 6]

lines = [
    "//! Prefixes that can never legitimately be the source of a packet.",
    "//!",
    "//! Generated by `scripts/gen-bogons.sh` from the IANA special-purpose registries.",
    "//! Do not edit by hand: `gen-bogons.sh --check` refuses a table that is not what the",
    "//! registries say, and a hand edit here is a rule nobody can trace back to a source.",
    "//!",
    "//! The RFC 1918 ranges are deliberately absent. A host behind NAT receives them, and",
    "//! dropping them by default is the false positive every bogon list has shipped at",
    "//! least once. The reasoning for each omission is in the script.",
    "",
    "use carapace_common::LpmKey;",
    "",
    f"pub const BOGONS: [LpmKey; {len(v4) + len(v6)}] = [",
]

for net, name, rfc in v4:
    octets = ", ".join(str(byte) for byte in net.network_address.packed)
    lines.append(f"    LpmKey::v4([{octets}], {net.prefixlen}), // {name}, {rfc}")

lines.append("")

for net, name, rfc in v6:
    word = f"0x{int(net.network_address):032x}"
    word = "_".join(word[2:][i : i + 8] for i in range(0, 32, 8))
    lines.append(
        f"    LpmKey::v6(0x{word}_u128.to_be_bytes(), {net.prefixlen}), "
        f"// {net.compressed}, {name}, {rfc}"
    )

lines.append("];")

sys.stdout.write("\n".join(lines) + "\n")
PY

# Through rustfmt, so the generated file is the one `cargo fmt --check` wants and the
# two checks can never disagree about the same table.
if ! command -v rustfmt >/dev/null; then
    printf 'gen-bogons: rustfmt is missing, and an unformatted table fails cargo fmt\n' >&2
    exit 2
fi
rustfmt --edition 2024 --config max_width=100 "$tmp/bogon_table.rs"

if [ "${1:-}" = --check ]; then
    if ! diff -u "$out" "$tmp/bogon_table.rs"; then
        printf 'gen-bogons: the committed table is not what the registries say; run %s\n' \
            "scripts/gen-bogons.sh" >&2
        exit 1
    fi
    printf 'gen-bogons: the committed table matches the registries\n'
    exit 0
fi

cp "$tmp/bogon_table.rs" "$out"
printf 'gen-bogons: wrote %s\n' "$out"
